---
# See https://github.com/actions/virtual-environments
# https://github.com/marketplace/actions/setup-perl-environment

name: Test Code
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '12 23 24 * *'
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        perl-version: ['5.32']  # add more versions if needed

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install Dependencies
        env:
          AUTOMATED_TESTING: 1
        run: |
          cpanm -iqn ExtUtils::MakeMaker Test::Most Test::Harness TAP::Harness::Env
          cpanm -iqn --skip-satisfied --installdeps --notest .

      - name: Run tests
        shell: bash
        run: prove -lv t/
        env:
          AUTOMATED_TESTING: 1
          NO_NETWORK_TESTING: 1
          NONINTERACTIVE_TESTING: 1

      - name: Show cpanm build log on failure (Windows)
        if: runner.os == 'Windows' && failure()
        shell: pwsh
        run: Get-Content "$env:USERPROFILE\.cpanm\work\*\build.log" -Tail 100
